%IronicSmiley	ITJ	%IronicSmiley
%Link	XY	%Link
%Mail	XY	%Mail
%NegSmiley	ITJ	%NegSmiley
%PosSmiley	ITJ	%PosSmiley
%Smiley	ITJ	%Smiley
%User	NE	%User
&lt;	$(	&lt;
&gt;	$(	&gt;
&amp;	$(	&amp;
&amp;&lt;	$(	&lt;
&amp;&gt;	$(	&gt;
