#!/usr/bin/env python2.7
# -*- coding: utf-8; -*-

##################################################################
# Libraries
import sys
import ld
from alt_argparse import argparser

##################################################################
# Processing Arguments
# note: some options are already set up by alt_argparser
argparser.description='Utility for replacing problematic Unicode characters with their equivalents.'
argparser.add_file_argument('-m', '--map-file', help='file from which character mappings should be loaded', \
                                required = True)
args = argparser.parse_args()

##################################################################
# Main Body
flsh      = args.flush
skip_line = args.skip_line
CHAR_MAP  = ld.Map(args.map_file)
i = 0
for file in args.files:
    line = file.readline().decode('utf-8')

    while line:
        line = line.strip()

        if line != skip_line:
            line = CHAR_MAP.replace(line)

        print line.encode('utf-8')
        if flsh:
            sys.stdout.flush()
        line = file.readline().decode('utf-8')
