#!/usr/bin/env python2.7

##################################################################
# Libraries
import re

from alt_argparse import argparser
from alt_fio import AltFileInput, AltFileOutput

##################################################################
# Variables and Constants
TABSEP  = re.compile(r'\t')
BARSEP  = re.compile(r'^([^|]+)\|')
COMASEP = re.compile(r',')
EMO_RE  = re.compile(r"[-:][])([*/]")
msg_id  = date = msg = ""

##################################################################
# Methods
def read_emo_list(ifile):
    """Read a list of emotionally tagged words from file."""
    words = []
    wset  = set([])
    for line in AltFileInput(ifile):
        line  = line.lower()
        words = TABSEP.split(line)
        words = [BARSEP.match(words[1]).group(1)] + COMASEP.split(words[-1])
        wset.update(words)
    ifile.close()
    return wset

##################################################################
# Arguments
argparser.description="""Utility for randomly choosing lines from a corpus
based on predefined criteria."""
argparser.add_file_argument("-l", "--list-file", """file with a list of emotional expressions""")
args = argparser.parse_args()

foutput = AltFileOutput(flush = args.flush)
finput  = AltFileInput(*args.files, skip_line = args.skip_line, \
                            skip_xml = args.skip_xml, \
                            print_func = foutput.fprint)

##################################################################
# Main
for line in finput:
    msg_id, date, msg = TABSEP.split(line)
