#!/usr/bin/env bash
# -*- mode: shell-script; -*-
set -e -o pipefail

character_normalizer -m "${SOCMEDIA_LSRC}/character_normalizer/char2char.map" $@ | \
umlaut_restorer -r "${SOCMEDIA_LSRC}/umlaut_restorer/misspelled_umlaut.re" \
    -m "${SOCMEDIA_LSRC}/umlaut_restorer/misspelled2umlaut.map" \
    -e "${SOCMEDIA_LSRC}/umlaut_restorer/umlaut_exceptions.dic" | \
sentence_splitter -k "${SOCMEDIA_LSRC}/sentence_splitter/keep.re" \
    -d "${SOCMEDIA_LSRC}/sentence_splitter/divide.re"
