#!/usr/bin/env python2.7
# -*- coding: utf-8; -*-

"""
Utility for determining sentence boundaries.
"""

##################################################################
# Importing Libraries
from alt_argparse import argparser
from alt_fio import AltFileInput, AltFileOutput
from sentence_splitter import SentenceSplitter

##################################################################
# Processing Arguments
argparser.description="""Utility for determining sentence boundaries."""
argparser.add_argument("-d", "--divide", help = """file with a list of regular
expressions which constitute a sentence boundary""")
argparser.add_argument("-k", "--keep", help = """file with exceptional regular
expressions where no sentence boundary should be made""")
argparser.add_argument("-x", "--skip-xml", help = "skip XML tags", \
                       action = "store_true")
argparser.add_argument("-v", "--verbose", help = "switch verbosity on", \
                       action = "store_true")
args = argparser.parse_args()

##################################################################
# Main Body
skip_xml  = args.skip_xml
debug     = args.verbose
ssplitter = SentenceSplitter(args.keep, args.divide, args.verbose)
foutput   = AltFileOutput(encoding = args.encoding, \
                          flush = args.flush)
finput    = AltFileInput(*args.files, \
                         skip_line = args.skip_line, \
                         skip_xml = args.skip_xml, \
                         print_func = foutput.fprint, \
                         errors = "replace")

for line in finput:
    output = ssplitter.split(line)
    foutput.fprint('\n'.join(output))
