#!/usr/bin/env python2.7
# -*- coding: utf-8; -*-

##################################################################
# Libraries
import sys

from ld.lingmap import lmap
from ld.p2p import P2P
from alt_argparse import argparser
from alt_fio import AltFileInput, AltFileOutput

##################################################################
# Processing Arguments
# note: some options are already set up by alt_argparser
argparser.description='Utility for replacing slang expression with their normalized forms.'
argparser.add_rule_file_argument('-m', '--map-file', \
                                     help='file from which phrase \
 mappings should be loaded', \
                                     file = "{SOCMEDIA_ROOT}/lingsrc/slang_normalizer/phrase2phrase.map")
args = argparser.parse_args()

##################################################################
# Main Body
SLANG_MAP = lmap.Map(args.map_file)
foutput   = AltFileOutput(encoding = args.encoding, \
                              flush = args.flush)
finput    = AltFileInput(*args.files, \
                              skip_line = args.skip_line, \
                              print_func = foutput.fprint, \
                              errors = 'replace')

for line in finput:
    line = SLANG_MAP.replace(line)
    foutput.fprint(line)
